version: "3.9"
services:
  arima:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: lambda_arima:dev
    ports:
      - 8080:8080
    volumes:
      - .:/usr/workspace:rw,delegated
    shm_size: 8gb
    command: python app.py
