version: "3.9"
services:
  arima:
    build:
        context: .
        dockerfile: Dockerfile
        target: dev
    ports:
      - 8080:8080
    volumes:
      - .:/usr/workspace:rw,delegated
    shm_size: 2gb
    command: python app.py
