version: "3.9"
services:
  arima:
    build:
        context: .
        dockerfile: Dockerfile
        target: dev
    ports:
      - 9000:8080
    volumes:
      - .:/var/task:rw,delegated
    command: app.handler
